[package]
name = "zero2prod"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "zero2prod"

[dependencies]
actix-http = "3.0.0-beta.14"
actix-web = "4.0.0-beta.13"

[dev-dependencies]
actix-rt = "2"
reqwest = "0.11"
tokio = "1"
